version: '2.1'
services:
  web:
    image: web-health
    build:
      context: /home/docker/health
      dockerfile: Dockerfile
    ports:
      - "80:80"    
    healthcheck:
      test: curl --fail http://13.40.72.6:80 || exit 1
      interval: 60s
      retries: 5
     #start_period: 20s
      timeout: 10s
